#!/bin/bash

echo "Intializing replica set on master"
replicate="rs.add(\"$1:27017\"); rs.add(\"$2:27017\", priority: 0.5 }); rs.status();"
docker exec -it $(docker ps -qf label=com.docker.swarm.service.name=overlay_mongo1) sh -c "echo '$replicate' | mongo"
